version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./drupal/web:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - drupal
    networks:
      - drupal_net

  drupal:
    image: drupal:11-php8.3-fpm
    volumes:
      - ./drupal/web:/var/www/html
    environment:
      - DRUPAL_DATABASE_HOST=db
      - DRUPAL_DATABASE_NAME=drupal
      - DRUPAL_DATABASE_USER=drupal
      - DRUPAL_DATABASE_PASSWORD=${DRUPAL_DATABASE_PASSWORD}
    depends_on:
      - db
    networks:
      - drupal_net

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - drupal_net

volumes:
  db_data:

networks:
  drupal_net:
